apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    iam.amazonaws.com/role: {{ .Values.aws_iam_role_arn }}
